### PR TITLE
#253: improve error handling for invalid parser versions

### LINKED ISSUE #253: wrong `--parser` version leads to a strange error message
If I run `eoc parse --parser=9.9.9`, I get a weird error:

```
$ eoc parse --parser=9.9.9
[ERROR] No plugin found for prefix 'eo' in the current project and in the plugin groups [org.sonatype.plugins, org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/yb/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
The command "/opt/homebrew/lib/node_modules/eolang/mvnw/mvnw eo:register -Deo.version=9.9.9 -Deo.hash=130afdd1456a0cbafd52aee8d7bc612e1faac547 --quiet -Deo.sourcesDir=/Volumes/sec/code/tmp/eo -Deo.targetDir=/Volumes/sec/code/tmp/eo/.eoc -Deo.outputDir=/Volumes/sec/code/tmp/eo/.eoc/classes -Deo.generatedDir=/Volumes/sec/code/tmp/eo/.eoc/generated-sources -Deo.placed=/Volumes/sec/code/tmp/eo/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

Let's try to report it a bit better.

### PR DESCRIPTION
**Pull request by vladislav-yevtushenko**
Fixes #253 by validating parser version against Maven Central before execution. When users specify an invalid version (e.g., --parser=9.9.9), they now receive a clear error message instead of a confusing Maven plugin resolution error.

Changes:
- Add exists() method to parser-version.js to check version availability
- Integrate validation in mvnw.js flags() function before Maven execution
- Provide helpful error message with link to available versions
- Gracefully handle network errors (validation falls back on network issues)

The validation makes an HTTP request to check if the POM file exists for the specified version. If the version doesn't exist, it shows: "Parser version X.X.X is not available in Maven Central" along with guidance on where to find valid versions.

### CODE REVIEW

**Comment by vladislav-yevtushenko** [comment]
@yegor256 please take a look when you have time

File: test/commands/test_parser_validation.js [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+ * SPDX-License-Identifier: MIT
+ */
+
+const assert = require('assert');
+const fs = require('fs');
+const path = require('path');
+const {execSync} = require('child_process');
+const {weAreOnline} = require('../helpers');
+
+describe('parser version validation', () => {
```
Comment (yegor256) [inline test/commands/test_parser_validation.js]: @vladislav-yevtushenko see this: https://www.yegor256.com/2023/01/19/layout-of-tests.html

Comment (vladislav-yevtushenko) [reply test/commands/test_parser_validation.js]: fixed I guess :)

File: test/commands/test_parser_validation.js [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+      'lint',
+      '--parser=999.999.999',
+      '-s', path.resolve(home, 'src'),
+      '-t', path.resolve(home, 'target'),
+    ].join(' '));
+
+    assert(result.status !== 0, 'Lint should fail with invalid version');
+    const output = result.stderr || result.stdout || result.error;
+    assert(
+      output.includes('is not available'),
```
[the remark this answers is not in the document]
Comment (vladislav-yevtushenko) [reply test/commands/test_parser_validation.js]: fixed

**Comment by yegor256** [comment]
@maxonfjvipon can you please take a look?

File: test/commands/test_parse.js [hunk 3]
```diff
@@ -34,4 +62,84 @@ describe('parse', () => {
...
+    const home = path.resolve('temp/test-parse/lint-invalid');
+    createTestProject(home);
+
+    const result = runCommand([
+      'lint',
+      '--parser=999.999.999',
+      '-s', path.resolve(home, 'src'),
+      '-t', path.resolve(home, 'target'),
+    ].join(' '));
+
```
Comment (maxonfjvipon) [inline test/commands/test_parse.js]: @vladislav-yevtushenko it's better not to leave empty lines inside function body: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

File: test/commands/test_parse.js [hunk 4]
```diff
@@ -6,16 +6,44 @@
...
 
+  const createTestProject = (dir) => {
+    fs.rmSync(dir, {recursive: true, force: true});
+    fs.mkdirSync(path.resolve(dir, 'src'), {recursive: true});
+    fs.writeFileSync(
+      path.resolve(dir, 'src/simple.eo'),
+      '# sample\n[] > simple\n'
+    );
+  };
+
```
Comment (maxonfjvipon) [inline test/commands/test_parse.js]: @vladislav-yevtushenko it's better not to leave empty lines inside function body: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

File: test/commands/test_parse.js [hunk 5]
```diff
@@ -6,16 +6,44 @@
...
+  const runCommand = (args) => {
```
Comment (maxonfjvipon) [inline test/commands/test_parse.js]: @vladislav-yevtushenko it seems we already have `runSync` command. Maybe it's better to modify it instead of creating almost the same one?

File: test/commands/test_parse.js [hunk 6]
```diff
@@ -34,4 +62,84 @@ describe('parse', () => {
...
+    const home = path.resolve('temp/test-parse/valid-version');
+    createTestProject(home);
+
+    const result = runCommand([
+      'parse',
+      '--parser=0.28.11',
+      '-s', path.resolve(home, 'src'),
+      '-t', path.resolve(home, 'target'),
+    ].join(' '));
+
```
Comment (maxonfjvipon) [inline test/commands/test_parse.js]: @vladislav-yevtushenko it's better not to leave empty lines inside function body: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

File: test/commands/test_parse.js [hunk 7]
```diff
@@ -34,4 +62,84 @@ describe('parse', () => {
     assert(!fs.existsSync(path.resolve('../../mvnw/target')));
     done();
   });
+
+  it('rejects invalid parser version', function () {
+    this.timeout(30000);
+    const home = path.resolve('temp/test-parse/invalid-version');
+    createTestProject(home);
+
```
[the remark this answers is not in the document]
Comment (vladislav-yevtushenko) [reply test/commands/test_parse.js]: fixed

File: test/commands/test_parse.js (hunk 5 above)
Comment (vladislav-yevtushenko) [reply test/commands/test_parse.js]: fixed

File: src/parser-version.js [hunk 8]
```diff
@@ -25,5 +25,25 @@ const request = require('sync-request'),
...
       return version.value;
+    },
+    /**
+     * Check if a specific parser version exists in Maven Central.
+     * @param {String} ver - Version to check, for example '0.23.1'
+     * @return {Boolean} True if version exists, false otherwise
+     */
+    exists(ver) {
+      if (!ver || ver === 'undefined') {
+        return false;
```
[the remark this answers is not in the document]
Comment (vladislav-yevtushenko) [reply src/parser-version.js]: fixed

**Comment by vladislav-yevtushenko** [comment]
@maxonfjvipon thanks for all your comments. fixed all of them.

**Comment by yegor256** [comment]
@vladislav-yevtushenko thanks!
