### PR TITLE
fix(#368): added utility function for elapsed time tracking

### LINKED ISSUE #368: we don't show timing in the main log output
Currently, I'm getting this:

```
$ eoc compile
EO objects registered in .eoc/eo-foreign.json
EO program assembled in .eoc
EO program verified in .eoc
Java sources generated in .eoc/generated-sources
Java .class files compiled into .eoc
```

Would be much better to see this:

```
EO objects registered in .eoc/eo-foreign.json in 34ms
EO program assembled in .eoc in 1s
EO program verified in .eoc in 340ms
Java sources generated in .eoc/generated-sources in 5s
Java .class files compiled into .eoc in 2s
```

Let's add the timings at the end of every logging line.

### PR DESCRIPTION
**Pull request by trapvpack**
closes #368 
@yegor256 take a look please

### CODE REVIEW

File: src/elapsed.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+            const duration = Date.now() - startTime;
+            let extended;
+            if (duration < 1000) {
+                extended = `${duration}ms`;
+            } else if (duration < 60 * 1000) {
+                extended = `${Math.ceil(duration / 1000)}s`;
+            } else {
+                extended = `${Math.ceil(duration / 3600000)}min`;
+            }
+            let msg = `${message} in ${extended}`;
```
Comment (maxonfjvipon) [inline src/elapsed.js:63]: @trapvpack I think `msg` can be `const` here

File: src/elapsed.js [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+ * seconds, or minutes, based on the duration.
+ *
+ * @param {Function} task - A callback function to be measured. The function
+ *                          is invoked with a `tracked` object as an argument.
+ * @return {*} Result of the wrapped callback function. The result of the
+ *             `task` callback will be returned unchanged.
+ */
+module.exports.elapsed = function elapsed(task) {
+    const startTime = Date.now();
+    const tracked = {
```
Comment (maxonfjvipon) [inline src/elapsed.js:52]: @trapvpack let's inline this variable into `task` call
```javascript
return task({
  print: (message) => {
    // code here
  }
})
```

File: test/test_elapsed.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+const {elapsed} = require('../src/elapsed')
+const assert = require("assert");
+
+describe('elapsed', function(){
+    const snooze = ms => new Promise(resolve => setTimeout(resolve, ms));
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:29]: @trapvpack let's follow a single code style and wrap lambda arguments with braces:
```
const snooze = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
```

File: test/test_elapsed.js [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    it('measures time correctly', async () => {
+        return elapsed(async (tracked) => {
+            await snooze(300);
+            return tracked.print("task");
+        }).then(
+            (actual)=> assert(
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:35]: @trapvpack space after `)` is missed here

File: test/test_elapsed.js [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+                /task in 30\d+ms/.test(actual),
+                `Expected "${actual}" to match /task in 30\\d+ms/`
+            )
+        )
+    });
+
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:41]: @trapvpack there's no need for space here

File: test/test_elapsed.js [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+            await snooze(10);
+            return tracked.print("short task");
+        }).then(
+            (actual) => assert(
+                /short task in 1\d+ms/.test(actual),
+                `Expected "${actual}" to match /short task in 1\\d+ms/`
+            )
+        );
+    });
+
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:53]: @trapvpack there's no need for space here

File: test/test_elapsed.js [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+            await snooze(1200);
+            return tracked.print("long task");
+        }).then(
+            (actual) => assert(
+                /long task in 2s/.test(actual),
+                `Expected "${actual}" to match /long task in 2s/`
+            )
+        );
+    });
+
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:65]: @trapvpack there's no need for space here

File: test/test_elapsed.js [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+    it('handles errors in task correctly', async () => {
+        try {
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:67]: @trapvpack I think the test can be simplified with `assert.throws()`

File: src/commands/assemble.js [hunk 9]
```diff
@@ -33,8 +34,10 @@ const {mvnw, flags} = require('../mvnw');
...
-    console.info('EO program assembled in %s', rel(target));
-    return r;
+  return elapsed((tracked) => {
+    return mvnw(['eo:assemble'].concat(flags(opts)), opts.target, opts.batch).then((r) => {
+      tracked.print('EO program assembled in %s', rel(target));
+      return r;
+    });
   });
-};
+};
```
Comment (maxonfjvipon) [inline src/commands/assemble.js:43]: @trapvpack this change is unnecessary

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Comment by trapvpack** [comment]
@maxonfjvipon take a look, I fixed what you asked for

**Comment by yegor256** [comment]
@trapvpack please, merge `master` branch into your branch - to make the build clean

**Comment by maxonfjvipon** [comment]
@trapvpack you didn't correct all the my comments and there are some new ones from `action-lint`

**Comment by trapvpack** [comment]
@maxonfjvipon, take a look, I think I closed all conversations. If I understood correctly, it was necessary to modify conversations without the outdated tag, correct me if this is wrong

**Comment by trapvpack** [comment]
@yegor256, I merged master into my branch, but it stiil dont complete a build checks. I assume this is due to the version being raised to 0.43.0, but tag is not upped, refers to [388](https://github.com/objectionary/eoc/issues/388)

**Comment by yegor256** [comment]
@trapvpack all builds are clean in the `master` branch now

**Comment by trapvpack** [comment]
@yegor256 @maxonfjvipon, take a look please

**Comment by trapvpack** [comment]
@yegor256 @maxonfjvipon, take a look please😎

File: src/commands/java/compile.js [hunk 10]
```diff
@@ -33,6 +33,10 @@ const path = require('path');
  */
 module.exports = function(opts) {
   const target = path.resolve(opts.target);
+  /**
+   * @todo #368:30min Wrap logs in 'elapsed'
+   * - It is necessary to use 'elapsed' in all logging cases that require output of elapsed time
```
Comment (maxonfjvipon) [inline src/commands/java/compile.js:38]: @trapvpack the format is still wrong, should be:
```
* @todo #368:30min Wrap logs in 'elapsed'
*  It is necessary to use 'elapsed' in all logging cases that require output of elapsed time
```

File: src/elapsed.js [hunk 11]
```diff
@@ -0,0 +1,69 @@
...
+/**
+ * @todo #368
+ * Consider if this method belong is in the right place.
+ * It might belong in a utility module.
+ * For now, it remains here.
+ *
+ * Also, review whether the test file for this method is located appropriately.
+ * It’s unclear if its current location is the best fit.
+ */
+
```
[the remark this answers is not in the document]
Comment (maxonfjvipon) [reply src/elapsed.js:32]: @trapvpack there's no need to split a comments

File: test/test_elapsed.js [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+const assert = require('assert');
+
+describe('elapsed', function() {
+  const snooze = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
+  it('measures time correctly', async () => {
+    return elapsed(async (tracked) => {
+      await snooze(300);
+      return tracked.print('task');
+    }) .then(
+      (actual)=> assert(
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:35]: @trapvpack the space after `(actual)` is missed

File: test/test_elapsed.js [hunk 13]
```diff
@@ -0,0 +1,76 @@
...
+        /task in 30\d+ms/.test(actual),
+        `Expected "${actual}" to match /task in 30\\d+ms/`
+      )
+    );
+  });
+  it('measures short time correctly', async () => {
+    return elapsed(async (tracked) => {
+      await snooze(10);
+      return tracked.print('short task');
+    }) .then(
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:45]: @trapvpack the space after `})` is unnecessary

File: test/test_elapsed.js [hunk 14]
```diff
@@ -0,0 +1,76 @@
...
+        /short task in 1\d+ms/.test(actual),
+        `Expected "${actual}" to match /short task in 1\\d+ms/`
+      )
+    );
+  });
+  it('measures long time correctly', async () => {
+    return elapsed(async (tracked) => {
+      await snooze(1200);
+      return tracked.print('long task');
+    }) .then(
```
Comment (maxonfjvipon) [inline test/test_elapsed.js:56]: @trapvpack the space after `})` is unnecessary

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Comment by trapvpack** [comment]
@maxonfjvipon, take a look please, thanks for your patience)

File: src/elapsed.js [hunk 15]
```diff
@@ -0,0 +1,63 @@
...
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+/**
+ * @todo #368:30min Decide if the `elapsed` utility function is in the right place
+ *  Consider relocating `elapsed` utility function and its test file if needed
+ */
+
```
Comment (maxonfjvipon) [inline src/elapsed.js:29]: @trapvpack once again, there's no need to split the comment, please join them into single one

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]
@trapvpack the last one I hope)

**Comment by trapvpack** [comment]
@maxonfjvipon, take a look please, I hope I understand correctly now

File: src/elapsed.js [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+/**
+ * @todo #368:30min Decide if the `elapsed` utility function is in the right place,
+ *  consider relocating it and its test file if needed
+ */
+
```
Comment (maxonfjvipon) [inline src/elapsed.js:29]: @trapvpack you have two comments section here stated with `/**` and ended with `*/`. The first comment is on lines 25-28, the second is on 30-44 and there's an empty line 29 between them. We don't need two comments here, it should one single comment started on line 25 and ended on line 43 or 44 with no empty lines. Also please move your todo under the function description

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]
@trapvpack let's try one more time

**Comment by trapvpack** [comment]
@maxonfjvipon, take a look please, thanks for the detailed explanation

File: src/elapsed.js [hunk 17]
```diff
@@ -0,0 +1,62 @@
...
+        extended = `${Math.ceil(duration / 3600000)}min`;
+      }
+      const msg = `${message} in ${extended}`;
+      console.info(msg);
+      return msg;
+    }
+  });
+};
+/**
+ * @todo #368:30min Decide if the `elapsed` utility function is in the right place,
```
Comment (maxonfjvipon) [inline src/elapsed.js:60]: @trapvpack now you have 2 comments again... it should be one: 
```

/**
 * A utility function to measure the elapsed time of a task and provide
 * detailed timing information.
 *
 * This function wraps a given task (callback function) and provides it with
 * a `tracked` object that includes a `print` method. The `print` method can
 * be used within the task to log messages along with the elapsed time
 * since the task started execution. The elapsed time is formatted in milliseconds,
 * seconds, or minutes, based on the duration.
 *
 * @param {Function} task - A callback function to be measured. The function
 *                          is invoked with a `tracked` object as an argument.
 * @return {*} Result of the wrapped callback function. The result of the
 *             `task` callback will be returned unchanged.
 * @todo #368:30min Decide if the `elapsed` utility function is in the right place,
 *  consider relocating it and its test file if needed
 */

```

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Comment by trapvpack** [comment]
@maxonfjvipon, take a look please

**Review by maxonfjvipon — APPROVED** [review]
@trapvpack now it looks good, thank you

**Comment by trapvpack** [comment]
@yegor256, take a look please:), thanks for attention

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@trapvpack @maxonfjvipon something is wrong here? Why it doesn't build after merge?

**Comment by maxonfjvipon** [comment]
@yegor256 it seems something wrong with `eo2js` here, I'll check this out

**Comment by trapvpack** [comment]
@maxonfjvipon is there anything I can do to help?

**Comment by maxonfjvipon** [comment]
@trapvpack let's wait for https://github.com/objectionary/eo2js/pull/121, I'll fix it as quite as possible

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@trapvpack thanks!!
